version: '2'
services:
    tasksjhipster-app:
        image: tasksjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tasksjhipster-mysql:3306/tasksjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tasksjhipster-mysql:
        extends:
            file: mysql.yml
            service: tasksjhipster-mysql
